### ISSUE TITLE
Improbable improvement ideas

### ISSUE THREAD

**Issue by Lysandr0** [CaptainObvious0/NoCheatPlus#20]
### Describe the features of this added check
I’d really appreciate to see a bunch of improvements being added to the Improbable check in the future if possible , firstly: more fine tuning, by allowing people to customise which checks can directly incur violations, which ones to only feed, how much weight it should have etc…
And secondly, allow SurvivalFly to (only) feed Improbable when a player is continuously triggering the check for really low violation levels (This may help fighting horizontal fly bypasses which exploit the VL relaxation mechanic of NCP when you don’t always set to cancel for lower VLs.)
### Any extra information about what should be added? (Config options...)
I'd imagine the config to look like this, more or less, although it may clog it quite a bit... :p

(If set to false, the check will only feed Improbable)
```
improbable:
      active: true
      level: 200
      checks:
        FastBreak:
          violation: true/false
              feed_weight: 0.7
        WrongBlock:
          violation: true/false
              feed_weight: 0.7
        InstantBow:
          violation: true/false
              feed_weight: 0.7
        YawRate:
          violation: true/false
              feed_weight: 0.7
       (...And so on...)
      actions: cancel (…)
```
Or, likewise the current InstantBow check, adding an "improbable" entry to every check that can feed it.

(Oh, and also, thank you a lot for continuing this project :) )
